config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  
    get '/landing', to: 'page#landing'
    get '/menu', to: 'page#menu'
    get '/hours', to: 'page#hours'
    get '/location', to: 'page#location'
    get '/cubed/:number', to: 'page#cubed'
    get '/evenly/:number1/:number2', to: 'page#evenly'
    get '/palindrome/:string', to:'page#palindrome'
    get '/random/:number1/:number2', to: 'page#random'
    get '/madlib/:noun/:verb/:adjective', to: 'page#madlib'
end

  # Defines the root path route ("/")
  # root "posts#index"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/page_controller.rb
class PageController < ApplicationController
    def landing 
    end
    def menu 
    end
    def hours
    end
    def location
    end
    def cubed 
        @number = params[:number].to_i * params[:number].to_i * params[:number].to_i

    end
    def evenly
        @number1 = params[:number1]
        @number2 = params[:number2]
        if (params[:number1].to_i % params[:number2].to_i).even?
            @outcome = 'number 1 is evenly divisible by number 2'
        else
            @outcome = 'number 1 is not evenly divisible by number 2'
        end 
    end
    def palindrome
        @string = params[:string]
        if (params[:string] == params[:string].reverse)
        @outcome = 'it is palindrome'
        else 
            @outcome = 'is not palindrome'
        end
    end
    def random
        @number1 = params[:number1].to_i
        @number2 = params[:number2].to_i
        
        if @number1 <= @number2
            @outcome = rand(@number1..@number2)
        else
            @outcome = 'Invalid input. Please ensure number1 is less than or equal to number2.'
        end
    end
        
    def madlib
        @noun = params[:noun]
        @verb = params[:verb]
        @adjective = params[:adjective]

        @story = "One day, a #{@adjective} #{@noun} decided to #{@verb} through the park. Everyone around couldn't believe their eyes as the #{@noun} #{@verb}ed in the most #{@adjective} way imaginable."
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsControllersRoutesViews</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/page/cubed.html.erb
<h3>Your number is now <%= @number %></h3>

app/views/page/evenly.html.erb
<h3><%= @outcome %></h3>
<p>Number 1: <%= @number1 %></p>
<p>Number 2: <%= @number2 %></p>

app/views/page/hours.html.erb
<h2>hours of operation</h2>
<ul>
<li>Monday-Friday 3pm to 10pm</li>
<li>Weekend 11am to 10pm</li>
<%= link_to 'menu', menu_path %>
<%= link_to 'location', location_path %>
<%= link_to 'landing', landing_path %>

app/views/page/landing.html.erb
<h1> Welcome to Pokie Page </h1>
<%= link_to 'See the Menu', menu_path %>
<%= link_to 'hours', hours_path %>
<%= link_to 'location', location_path %>

app/views/page/location.html.erb
<h1>1527 Rodeo Drive, La California</h1>
<%= link_to 'hours', hours_path %>
<%= link_to 'menu', menu_path %>
<%= link_to 'landing', landing_path %>

app/views/page/madlib.html.erb
<h4>madlib</h4>
<p><%= @story %></p>

app/views/page/menu.html.erb
<h2>Traditional Vietnamese Braised Fish</h2>
<ul>
  <li>Lemongrass Stir-Fry</li>
  <li>Tofu Pad Thai</li>
  <li>Hot N Spicy Pho</li>
</ul>
<%= link_to 'hours', hours_path %>
<%= link_to 'location', location_path %>
<%= link_to 'landing', landing_path %>

app/views/page/palindrome.html.erb
<h4>palindrome</h4>
<h3><%= @outcome %></h3>

app/views/page/random.html.erb
<h4>random</h4>
<h3> <%= @outcome %> </h3>